src/Entity/Chantier.php
<?php

namespace App\Entity;

use App\Repository\ChantierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChantierRepository::class)
 */
class Chantier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $addresse;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\OneToMany(targetEntity=Pointages::class, mappedBy="id_chantier")
     */
    private $pointages;

    public function __construct()
    {
        $this->pointages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAddresse(): ?string
    {
        return $this->addresse;
    }

    public function setAddresse(string $addresse): self
    {
        $this->addresse = $addresse;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    /**
     * @return Collection|Pointages[]
     */
    public function getPointages(): Collection
    {
        return $this->pointages;
    }

    public function addPointage(Pointages $pointage): self
    {
        if (!$this->pointages->contains($pointage)) {
            $this->pointages[] = $pointage;
            $pointage->setIdChantier($this);
        }

        return $this;
    }

    public function removePointage(Pointages $pointage): self
    {
        if ($this->pointages->removeElement($pointage)) {
            // set the owning side to null (unless already changed)
            if ($pointage->getIdChantier() === $this) {
                $pointage->setIdChantier(null);
            }
        }

        return $this;
    }
}

src/Form/ChantierType.php
<?php

namespace App\Form;

use App\Entity\Chantier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChantierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('addresse')
            ->add('date_debut')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Chantier::class,
        ]);
    }
}

src/Controller/ChantierController.php
<?php

namespace App\Controller;

use App\Entity\Chantier;
use App\Form\ChantierType;
use App\Repository\ChantierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/chantier")
 */
class ChantierController extends AbstractController
{
    /**
     * @Route("/", name="chantier_index", methods={"GET"})
     */
    public function index(ChantierRepository $chantierRepository): Response
    {
        $nb_de_utilisateur_par_chantier = [];
        $nb_duree = [];
        foreach ($chantierRepository->findAll() as $chantier){
            $nb_de_utilisateur = [];
            $totalSeconde = 0;
            $totalMinute = 0;
            $totalHeure = 0;
            foreach ($chantier->getPointages() as $pointage){
                if (!in_array($pointage->getIdUtilisateur()->getNom(),$nb_de_utilisateur)){
                    $nb_de_utilisateur[] = $pointage->getIdUtilisateur()->getNom();
                }
                $totalHeure += intval( $pointage->getDuree()->format('H'));
                $totalMinute += intval( $pointage->getDuree()->format('i'));
                $totalSeconde += intval($pointage->getDuree()->format('s'));
            }
            $string_duree_create = strval($totalHeure)." : ";
            if ($totalMinute<10){
                $string_duree_create.="0".strval($totalMinute);
            }else{
                $string_duree_create.=strval($totalMinute);
            }
            $string_duree_create.=" : 0".strval($totalSeconde);
            $nb_duree[$chantier->getNom()] = $string_duree_create;
            $nb_de_utilisateur_par_chantier[$chantier->getNom()] = $nb_de_utilisateur;
        }

        return $this->render('chantier/index.html.twig', [
            'chantiers' => $chantierRepository->findAll(),
            'nb_user' => $nb_de_utilisateur_par_chantier,
            'total_duree' => $nb_duree
        ]);
    }

    /**
     * @Route("/new", name="chantier_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $chantier = new Chantier();
        $form = $this->createForm(ChantierType::class, $chantier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($chantier);
            $entityManager->flush();

            return $this->redirectToRoute('chantier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('chantier/new.html.twig', [
            'chantier' => $chantier,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="chantier_show", methods={"GET"})
     */
    public function show(Chantier $chantier): Response
    {
        $nb_de_utilisateur = [];
        foreach ($chantier->getPointages() as $pointage){
            if (!in_array($pointage->getIdUtilisateur()->getNom(),$nb_de_utilisateur)){
                $nb_de_utilisateur[] = $pointage->getIdUtilisateur()->getNom();
            }
        }

        return $this->render('chantier/show.html.twig', [
            'chantier' => $chantier,
            'nb_utilisateur'=>$nb_de_utilisateur
        ]);
    }

    /**
     * @Route("/{id}/edit", name="chantier_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Chantier $chantier, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ChantierType::class, $chantier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('chantier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('chantier/edit.html.twig', [
            'chantier' => $chantier,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="chantier_delete", methods={"POST"})
     */
    public function delete(Request $request, Chantier $chantier, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$chantier->getId(), $request->request->get('_token'))) {
            $entityManager->remove($chantier);
            $entityManager->flush();
        }

        return $this->redirectToRoute('chantier_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/chantier/_delete_form.html.twig
<form method="post" action="{{ path('chantier_delete', {'id': chantier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chantier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/chantier/_form.html.twig
{{ form_start(form) }}
    <p style="color: red"> {{ form_errors(form) }}</p>
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/chantier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Chantier{% endblock %}

{% block body %}
    <h1>Edit Chantier</h1>

    {{ include('chantier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('chantier_index') }}">back to list</a>

    {{ include('chantier/_delete_form.html.twig') }}
{% endblock %}

templates/chantier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chantier index{% endblock %}

{% block body %}
    <a href="{{ path('utilisateur_index') }}">Page utilisateur</a>
    <a href="{{ path('pointages_index') }}">Page pointages</a>
    <h1>Chantier</h1>

    <table class="table" style="width: 60%;">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Addresse</th>
                <th>Date_debut</th>
                <th>Actions</th>
                <th>Nombre de personne</th>
                <th>Nombre d'heures cumulés</th>
            </tr>
        </thead>
        <tbody style="text-align: center; vertical-align: middle;">
        {% set nb_de_utilisateur_par_chantier = [] %}
        {% for chantier in chantiers %}
            <tr>
                <td>{{ chantier.nom }}</td>
                <td>{{ chantier.addresse }}</td>
                <td>{{ chantier.dateDebut ? chantier.dateDebut|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('chantier_show', {'id': chantier.id}) }}">show</a>
                    <a href="{{ path('chantier_edit', {'id': chantier.id}) }}">edit</a>
                    {{ include('chantier/_delete_form.html.twig') }}
                </td>
                <td>
                    {{ nb_user[chantier.nom]|length }}
                </td>
                <td>
                    {{ total_duree[chantier.nom] }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('chantier_new') }}">Create new</a>
{% endblock %}

templates/chantier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Chantier{% endblock %}

{% block body %}
    <h1>Create new Chantier</h1>

    {{ include('chantier/_form.html.twig') }}

    <a href="{{ path('chantier_index') }}">back to list</a>
{% endblock %}

templates/chantier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chantier{% endblock %}

{% block body %}
    <a href="{{ path('chantier_index') }}">back to list</a>
    <h1>Chantier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom : </th>
                <td>{{ chantier.nom }}</td>
            </tr>
            <tr>
                <th>Addresse : </th>
                <td>{{ chantier.addresse }}</td>
            </tr>
            <tr>
                <th>Date_debut : </th>
                <td>{{ chantier.dateDebut ? chantier.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
        <tr>
            <th>Nombre d'utilisateur sur ce chantier : </th>
            <td>{{ nb_utilisateur|length }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('chantier_edit', {'id': chantier.id}) }}">edit</a>

    {{ include('chantier/_delete_form.html.twig') }}
{% endblock %}