src/Entity/Pointages.php
<?php

namespace App\Entity;

use App\Repository\PointagesRepository;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator as MyConstraints;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PointagesRepository::class)
 * @UniqueEntity(
 *     fields={"date", "id_utilisateur"}
 * )
 * @MyConstraints\Time
 */
class Pointages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="time")
     */
    private $duree;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="pointages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity=Chantier::class, inversedBy="pointages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_chantier;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(\DateTimeInterface $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getIdUtilisateur(): ?Utilisateur
    {
        return $this->id_utilisateur;
    }

    public function setIdUtilisateur(?Utilisateur $id_utilisateur): self
    {
        $this->id_utilisateur = $id_utilisateur;

        return $this;
    }

    public function getIdChantier(): ?Chantier
    {
        return $this->id_chantier;
    }

    public function setIdChantier(?Chantier $id_chantier): self
    {
        $this->id_chantier = $id_chantier;

        return $this;
    }
}

src/Form/PointagesType.php
<?php

namespace App\Form;

use App\Entity\Pointages;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PointagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('duree')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pointages::class,
        ]);
    }
}

src/Controller/PointagesController.php
<?php

namespace App\Controller;

use App\Entity\Pointages;
use App\Form\PointagesType;
use App\Form\UtilisateurType;
use App\Repository\ChantierRepository;
use App\Repository\PointagesRepository;
use App\Repository\UtilisateurRepository;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/pointages")
 */
class PointagesController extends AbstractController
{
    /**
     * @Route("/", name="pointages_index", methods={"GET"})
     */
    public function index(PointagesRepository $pointagesRepository): Response
    {
        //var_dump($pointagesRepository->count(["id_utilisateur"=>1]));
        return $this->render('pointages/index.html.twig', [
            'pointages' => $pointagesRepository->findAll(),
            //'list' => $pointagesRepository->findCountHours(7)
        ]);
    }

    /**
     * @Route("/new", name="pointages_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, UtilisateurRepository $utilisateurRepository, ChantierRepository $chantierRepository): Response
    {
        $pointage = new Pointages();

        $form = $this->createForm(PointagesType::class, $pointage);

        $list_user = [];
        foreach ($utilisateurRepository->findAll() as $user){
            $list_user[$user->getNom()." ".$user->getPrenom()] = $user;
        }
        $form->add('id_utilisateur',ChoiceType::class, [
            'choices' => $list_user
        ]);

        $list_chantier = [];
        foreach ($chantierRepository->findAll() as $chantier){
            $list_chantier[$chantier->getNom()] = $chantier;
        }
        $form->add('id_chantier',ChoiceType::class,[
            'choices' => $list_chantier
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($pointage);
            $entityManager->flush();

            return $this->redirectToRoute('pointages_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pointages/new.html.twig', [
            'pointage' => $pointage,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="pointages_show", methods={"GET"})
     */
    public function show(Pointages $pointage): Response
    {
        return $this->render('pointages/show.html.twig', [
            'pointage' => $pointage,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="pointages_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Pointages $pointage,
                         EntityManagerInterface $entityManager,
                         UtilisateurRepository $utilisateurRepository,
                         ChantierRepository $chantierRepository): Response
    {
        $form = $this->createForm(PointagesType::class, $pointage);
        $list_user = [];
        foreach ($utilisateurRepository->findAll() as $user){
            $list_user[$user->getNom()." ".$user->getPrenom()] = $user;
        }
        $form->add('id_utilisateur',ChoiceType::class, [
            'choices' => $list_user
        ]);
        $list_chantier = [];
        foreach ($chantierRepository->findAll() as $chantier){
            $list_chantier[$chantier->getNom()] = $chantier;
        }
        $form->add('id_chantier',ChoiceType::class,[
            'choices' => $list_chantier
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('pointages_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pointages/edit.html.twig', [
            'pointage' => $pointage,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="pointages_delete", methods={"POST"})
     */
    public function delete(Request $request, Pointages $pointage, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pointage->getId(), $request->request->get('_token'))) {
            $entityManager->remove($pointage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('pointages_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/pointages/_delete_form.html.twig
<form method="post" action="{{ path('pointages_delete', {'id': pointage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pointage.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pointages/_form.html.twig
{{ form_start(form) }}
{% set formErrors = form.vars.errors.form.getErrors(true) %}
{% if formErrors|length %}
    <ul>
        {% for error in formErrors %}
            <li style="color: red">{{ error.message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pointages/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pointages{% endblock %}

{% block body %}
    <a href="{{ path('pointages_index') }}">back to list</a>
    <h1>Edit Pointages</h1>

    {{ include('pointages/_form.html.twig', {'button_label': 'Update'}) }}


    {{ include('pointages/_delete_form.html.twig') }}
{% endblock %}

templates/pointages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pointage{% endblock %}

{% block body %}
    <a href="{{ path('utilisateur_index') }}">Page utilisateur</a>
    <a href="{{ path('chantier_index') }}">Page chantier</a>
    <h1>Pointages index</h1>

    <a href="{{ path('pointages_new') }}">Créer un nouveaux pointage</a>
    <table class="table" style="width: 50%; text-align: center;">
        <thead>
            <tr>
                <th>Utilisateur</th>
                <th>Chantier</th>
                <th>Date</th>
                <th>Duree</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pointage in pointages %}
            <tr>
                <td>{{ pointage.idUtilisateur.nom }} {{ pointage.idUtilisateur.prenom }}</td>
                <td>{{ pointage.idChantier.nom }}</td>
                <td>{{ pointage.date ? pointage.date|date('Y-m-d') : '' }}</td>
                <td>{{ pointage.duree ? pointage.duree|date('H:i') : '' }}</td>
                <td>
                    <a href="{{ path('pointages_show', {'id': pointage.id}) }}">show</a>
                    <a href="{{ path('pointages_edit', {'id': pointage.id}) }}">edit</a>
                    {{ include('pointages/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/pointages/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pointages{% endblock %}

{% block body %}
    <a href="{{ path('pointages_index') }}">back to list</a>
    <h1>Create new Pointages</h1>

    {{ include('pointages/_form.html.twig') }}

{% endblock %}

templates/pointages/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pointages{% endblock %}

{% block body %}
    <a href="{{ path('pointages_index') }}">back to list</a>

    <h1>Pointages</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Date</th>
                <td>{{ pointage.date ? pointage.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Duree</th>
                <td>{{ pointage.duree ? pointage.duree|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Utilisateur</th>
                <td>{{ pointage.idUtilisateur.nom }} {{ pointage.idUtilisateur.prenom }}</td>
            </tr>
            <tr>
                <th>Chantier</th>
                <td>{{ pointage.idChantier.nom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('pointages_edit', {'id': pointage.id}) }}">edit</a>

    {{ include('pointages/_delete_form.html.twig') }}
{% endblock %}